- name: Playbook to import the virtual machine disk
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: import-from-url
    when: _apb_plan_id == 'url'
  vars:
    action: provision
    cluster: openshift